# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- "*"

stages:
  - stage: test
    jobs:
      - job: 'validateandtest'
        pool:
          vmimage: windows-latest
        steps:
        - task: AzureResourceManagerTemplateDeployment@3
          inputs:
            deploymentScope: 'Resource Group'
            azureResourceManagerConnection: 'devsecops_bench-sandbox-000-rg-000-connection'
            subscriptionId: '272192c4-fcb8-4863-9cbf-a00913d42b07'
            action: 'Create Or Update Resource Group'
            resourceGroupName: 'devsecops_bench-sandbox-000-rg-000'
            location: 'East US'
            templateLocation: 'Linked artifact'
            csmFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.json'
            csmParametersFile: '$(Build.SourcesDirectory)/StorageAccount/azuredeploy.parameters.json'
            deploymentMode: 'Validation'
        - task: PowerShell@2
          inputs:
            targetType: 'inline'
            script: 'Install-Module Az.Resources -RequiredVersion 1.12.1-preview -AllowPrerelease -Force -Scope CurrentUser'
        - task: AzurePowerShell@5
          inputs:
            azureSubscription: 'devsecops_bench-sandbox-000-rg-000-connection'
            ScriptType: 'InlineScript'
            Inline: |
              $Parameters = @{
                ResourcegroupName     = "ARMDeploymentTest"
                Templatefile          = ".\StorageAccount\azuredeploy.json"
                TemplateParameterfile = ".\StorageAccount\azuredeploy.parameters.json"
                Mode                  = 'Incremental'
               }
              $Result = Get-AzResourceGroupDeploymentWhatIfResult @Parameters
              $Result
            azurePowerShellVersion: 'LatestVersion'
        - task: AzurePowerShell@5
          displayName: "Check for deletion"
          inputs:
            azureSubscription: 'devsecops_bench-sandbox-000-rg-000-connection'
            ScriptType: 'FilePath'
            ScriptPath: '$(Build.SourcesDirectory)/Tests/CheckForDeletion.ps1'
            ScriptArguments: '-ResourceGroup ARMDeploymentTest'
            FailOnStandardError: true
            azurePowerShellVersion: 'LatestVersion'
        